# Generated by Django 5.1.3 on 2024-11-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WeatherAPP", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
